name: shelf_graphql
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  freezed_annotation: ^0.14.3

  gql:
  graphql_server:
    path: ../graphql_angel/graphql_server
  http_parser:
  http_server:

  json_annotation: ^4.1.0
  oxidized: ^5.0.1

  shelf:
  shelf_web_socket:

dev_dependencies:
  build_runner:
  freezed: ^0.14.5
  http:
  json_serializable: ^5.0.0
  lint: ^1.0.0

  shelf_plus: ^0.0.2
  shelf_router:
  shelf_static:

  test: ^1.14.4

dependency_overrides:
  graphql_schema:
    path: ../graphql_angel/graphql_schema