name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.0.0
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  json_path:
  oxidized: ^5.0.1
  blurhash_dart: ^1.0.2
  metadata_fetch: ^0.4.1
  linkify: ^4.1.0

  valida:
    path: ../../../valida/valida

  query_builder:
    path: ../../../query_builder

  sqlite3: ^1.3.1
  mysql1: ^0.19.2
  postgres: ^2.4.1+2

  argon2: ^1.0.1
  jose: ^0.3.2

  uuid:
  collection:

  shelf_cors_headers: ^0.1.2
  shelf_plus: ^0.0.2
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0
  shelf_graphql:
    path: ../..

  shelf_graphql_example:
    path: ../../example

dev_dependencies:
  build_runner: ^2.1.1
  freezed: ^0.14.5
  http: ^0.13.3
  json_serializable: ^5.0.0
  lint: ^1.0.0
  test_process: ^2.0.0
  test: ^1.14.4
  graphql_generator:
    path: ../../../graphql_server/graphql_generator
  valida_generator:
    path: ../../../valida/valida_generator
  query_builder_generator:
    path: ../../../query_builder/query_builder_generator

dependency_overrides:
  graphql_schema:
    path: ../../../graphql_server/graphql_schema
